image_finetune: false

output_dir: "outputs"
pretrained_model_path: "/mnt/newdrive/models/miniSD"

unet_additional_kwargs:
  in_channels: 8
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false
  motion_module_mid_block: true

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : false
    upcast_attention                   : true

noise_scheduler_kwargs:
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  beta_start: 0.00085
  clip_sample: false
  clip_sample_range: 1.0
  dynamic_thresholding_ratio: 0.995
  num_train_timesteps: 1000
  prediction_type: "epsilon"
  sample_max_value: 1.0
  set_alpha_to_one: false
  steps_offset: 1
  thresholding: false
  trained_betas: null

train_data:
  csv_path:        "data/output.csv"
  video_folder:    "data/videos"
  sample_size:     256
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "Close Up portrait of a woman swaying in front of a lake artwork by Kawase Hasui"
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules"

unet_checkpoint_path: ""

learning_rate:    1e-6
train_batch_size: 4
gradient_checkpointing: True
gradient_accumulation_steps: 4
adam_weight_decay: 1.e-2
lr_scheduler: "constant"
lr_warmup_steps: 0
scale_lr: true

max_train_epoch:     4
max_train_steps:      -1
checkpointing_epochs: -1
checkpointing_steps:  500

validation_steps:       100
validation_steps_tuple: []

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: False

is_debug: False
num_workers: 32