image_finetune: false

output_dir: "outputs"
pretrained_model_path: "/mnt/newdrive/automatic1111/models/Stable-diffusion/instruct-pix2pix-00-22000.ckpt"

unet_additional_kwargs:
  in_channels: 8
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : false

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path:        "data/output.csv"
  video_folder:    "data/videos"
  sample_size:     256
  sample_stride:   1
  sample_n_frames: 16

validation_data:
  prompts:
    - "make her smile"
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

learning_rate:    1.e-7
train_batch_size: 1
gradient_checkpointing: True
gradient_accumulation_steps: 4

max_train_epoch:      -1
max_train_steps:      10000
checkpointing_epochs: -1
checkpointing_steps:  1000

validation_steps:       250
validation_steps_tuple: []

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: False

is_debug: False
num_workers: 32